default:
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('LAKE_PATH') }}"
      threads: 16
      settings:
        enable_object_cache: true
        enable_http_metadata_cache: true
  target: dev
