default:
  outputs:
    dev:
      type: duckdb
      path: "/home/christianocean/mta/mta/mtastats/sources/mta/mtastats.duckdb"
      threads: 16
      settings:
        enable_object_cache: true
        enable_http_metadata_cache: true
  target: dev
